# Generated by Django 5.2.4 on 2025-08-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('unit', models.CharField(blank=True, help_text='단위(봉, 단, kg 등)', max_length=20, verbose_name='단위')),
            ],
        ),
    ]
