# Generated by Django 5.2.4 on 2025-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, help_text='단위(봉, 단, kg 등)', max_length=20),
        ),
    ]
