# Generated by Django 5.2.4 on 2025-08-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_description_remove_item_unit'),
        ('shopping', '0002_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shopping.ingredient'),
        ),
    ]
