# Generated by Django 5.2.4 on 2025-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredient',
        ),
    ]
