# Generated by Django 5.2.5 on 2025-08-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0002_initial"),
        ("reviews", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewkeywordmap",
            name="keyword",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_maps",
                to="reviews.reviewkeyword",
            ),
        ),
        migrations.AddField(
            model_name="reviewkeywordmap",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_maps",
                to="reviews.review",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["store"], name="reviews_rev_store_i_e37743_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["author"], name="reviews_rev_author__84fa2f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="review_rating_1_5",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewkeywordmap",
            unique_together={("review", "keyword")},
        ),
    ]
