# Generated by Django 5.2.4 on 2025-08-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewImage",
        ),
        migrations.DeleteModel(
            name="ReviewKeyword",
        ),
        migrations.DeleteModel(
            name="ReviewKeywordMap",
        ),
    ]
