# Generated by Django 5.2.4 on 2025-08-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_initial'),
        ('reviews', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.buyer'),
        ),
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store', '-created_at'], name='reviews_rev_store_i_2b8862_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', '-created_at'], name='reviews_rev_author__8385c0_idx'),
        ),
    ]
