# Generated by Django 5.2.5 on 2025-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShoppingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUGGESTED", "추천완료"),
                            ("PARTIAL_RESERVED", "일부예약"),
                            ("RESERVED", "전체예약완료"),
                            ("DONE", "완료"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=50)),
                ("ai_prompt", models.TextField(blank=True)),
                ("ai_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100)),
                ("quantity", models.FloatField(default=1.0)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("expected_unit_price", models.PositiveIntegerField(default=0)),
                ("expected_store_name", models.CharField(blank=True, max_length=100)),
                ("is_reserved", models.BooleanField(default=False)),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                ("memo", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
    ]
