# Generated by Django 5.2.5 on 2025-08-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0002_initial"),
        ("shopping", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingplan",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_plans",
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="shoppingplanitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shopping.shoppingplan",
            ),
        ),
        migrations.AddField(
            model_name="shoppingplanitem",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_items",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="shoppingplanitem",
            name="reservation_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_items",
                to="reservations.reservationitem",
            ),
        ),
        migrations.AddField(
            model_name="shoppingplanitem",
            name="suggested_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_plan_items",
                to="users.store",
            ),
        ),
    ]
