# Generated by Django 5.2.4 on 2025-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_ingredient'),
        ('shopping', '0002_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
