# Generated by Django 5.2.4 on 2025-08-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0002_delete_shoppingplan_delete_shoppingplanitem'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='재료명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='재료 설명')),
            ],
            options={
                'verbose_name': '재료',
                'verbose_name_plural': '재료 목록',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='상품 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품 설명')),
                ('is_available', models.BooleanField(default=True, verbose_name='판매중 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shopping.ingredient', verbose_name='기본 재료')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='판매 가게')),
            ],
            options={
                'verbose_name': '판매 상품',
                'verbose_name_plural': '판매 상품 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
