# Generated by Django 5.2.4 on 2025-08-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '__first__'),
        ('users', '0006_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('business_number', models.CharField(blank=True, max_length=20, null=True)),
                ('price_info', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_days', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_methods', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='users.seller')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='items.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='stores', through='stores.StoreItem', to='items.item'),
        ),
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_reports/')),
                ('food_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='reports', to='items.item')),
                ('keywords', models.ManyToManyField(blank=True, related_name='reports', to='stores.keyword')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.buyer')),
            ],
        ),
    ]
