# Generated by Django 5.2.4 on 2025-08-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
