# Generated by Django 5.2.4 on 2025-08-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='users.seller'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='items.item'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='stores.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='stores', through='stores.StoreItem', to='items.item'),
        ),
        migrations.AddField(
            model_name='storereport',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='reports', to='stores.keyword'),
        ),
        migrations.AddField(
            model_name='storereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.buyer'),
        ),
    ]
