# Generated by Django 5.2.4 on 2025-08-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("stores", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="users.seller",
            ),
        ),
        migrations.AddField(
            model_name="storereport",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="items.item"
            ),
        ),
        migrations.AddField(
            model_name="storereport",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="stores.keyword"
            ),
        ),
        migrations.AddField(
            model_name="storereport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="users.buyer",
            ),
        ),
    ]
