# Generated by Django 5.2.4 on 2025-08-14 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_price_info'),
        ('users', '0006_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='photo',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='users.seller'),
        ),
    ]
