# Generated by Django 5.2.4 on 2025-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='경도'),
        ),
    ]
