# Generated by Django 5.2.4 on 2025-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_photo_storeitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='store_photos/'),
        ),
    ]
