# Generated by Django 5.2.4 on 2025-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_description_remove_item_unit'),
        ('stores', '0004_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereport',
            name='food_type',
        ),
        migrations.AlterField(
            model_name='storereport',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='store_reports', to='items.item'),
        ),
    ]
