# Generated by Django 5.2.4 on 2025-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storereport_food_type_alter_storereport_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereport',
            name='items',
        ),
        migrations.AddField(
            model_name='storereport',
            name='report_items',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
