# Generated by Django 5.2.4 on 2025-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_storereport_items_storereport_report_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='storereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
    ]
