# Generated by Django 5.2.4 on 2025-08-18 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reward', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stamp_count', models.IntegerField(default=0)),
                ('medal_tier', models.CharField(choices=[('NONE', '없음'), ('BRONZE', '동메달'), ('SILVER', '은메달'), ('GOLD', '금메달')], default='NONE', max_length=10)),
                ('character_level', models.IntegerField(default=1)),
            ],
        ),
    ]
