# Generated by Django 5.2.4 on 2025-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='character_name',
            field=models.CharField(default='브로브로콜리', max_length=50),
        ),
    ]
