# Generated by Django 5.2.4 on 2025-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_pickup_at', models.DateTimeField(help_text='구매자가 희망한 픽업 시간')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ACCEPTED', '수락'), ('REJECTED', '거절'), ('PREPARING', '준비중'), ('READY', '픽업준비완료'), ('PICKED_UP', '픽업완료'), ('CANCELLED', '구매자취소'), ('EXPIRED', '만료')], default='PENDING', max_length=20)),
                ('rejected_reason', models.CharField(blank=True, choices=[('OUT_OF_STOCK', '재고 소진'), ('CLOSED_TODAY', '금일 영업 종료'), ('CLOSING_SOON', '판매 시간 종료'), ('TIME_UNAVAILABLE', '예약 시간 불가'), ('TEMP_CLOSED', '일시적 휴무'), ('FIELD_ISSUE', '날씨/현장상황'), ('OTHER', '기타')], max_length=30)),
                ('cancelled_reason', models.CharField(blank=True, max_length=200)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField(default=0, help_text='예약 시점 총액(원)')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('display_image', models.ImageField(blank=True, upload_to='reservations/cover/%Y/%m/%d/')),
                ('reservation_code', models.CharField(blank=True, db_index=True, max_length=12, unique=True)),
                ('seller_note', models.CharField(blank=True, max_length=200)),
                ('prep_eta_minutes', models.PositiveSmallIntegerField(default=0, help_text='준비 예상 소요 분')),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True)),
                ('point_rewarded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('unit_price', models.PositiveIntegerField(help_text='개당 가격(원, 스냅샷)')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, help_text='단위(봉, 단, kg 등)', max_length=20)),
                ('memo', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='reservations/items/%Y/%m/%d/')),
            ],
        ),
    ]
