# Generated by Django 5.2.4 on 2025-08-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_seller_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
