# Generated by Django 5.2.4 on 2025-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='has_store',
            field=models.BooleanField(default=False),
        ),
    ]
