# Generated by Django 5.2.4 on 2025-08-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('reservations', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.buyer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stores.store'),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_items', to='items.item'),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'status'], name='reservation_store_i_c96bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['buyer', 'status'], name='reservation_buyer_i_07ac1d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['requested_pickup_at'], name='reservation_request_c5741a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='unit_price_gte_0'),
        ),
    ]
