# Generated by Django 5.2.5 on 2025-08-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="users.buyer",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="reservationitem",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="reservations.reservation",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["store", "status"], name="reservation_store_i_c96bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["buyer", "status"], name="reservation_buyer_i_07ac1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["requested_pickup_at"], name="reservation_request_c5741a_idx"
            ),
        ),
    ]
