# Generated by Django 5.2.4 on 2025-08-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('reservations', '0003_alter_reservation_buyer_and_more'),
        ('stores', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_items', to='items.item'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.buyer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stores.store'),
        ),
    ]
