# Generated by Django 5.2.4 on 2025-08-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservationitem_original_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rejected_reason_detail',
        ),
    ]
